version: "3.8"

services:
  webapp:
    image: gradle:7.4-alpine
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - dev
    volumes:
      - ./:/app
    working_dir: /app
    command: gradle bootRun --no-daemon

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: docker-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  dev:
