spring:
  datasource:
    url: jdbc:postgresql://db:5432/docker-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_default: false
        show_sql: true
    hibernate:
      ddl-auto: create-drop
